### ISSUE TITLE
`[minigame round outcome]` is invisible for some agents

### ISSUE THREAD

**Issue by cth127** [google-deepmind/concordia#102]
For the `reality_show` environment, both `prisoners_dillema` and `stag_hunt`, `[minigame round outcome]` observation is visible for only some of the agents. 

For example,

![image](https://github.com/user-attachments/assets/35dbb427-034d-41db-a85b-d3b092802598)
![image](https://github.com/user-attachments/assets/1085de72-7490-4e73-8d5a-d0466ff2f136)
![image](https://github.com/user-attachments/assets/6350d867-584e-4558-8726-2b39d7282029)

Travis Pearson and Chad Donovan observes the outcome for the previous round, while Derek Wolfe cannot.
These three agents are all the same type of baseline agents: `paranoid_agent`.
Maybe `concurrency` caused this issue, or concurrence of observation time and action time (2003-07-09 06:20:00) could cause this.

**Comment by jzleibo** [comment]
I've just submitted a fix for this here: https://github.com/google-deepmind/concordia/commit/cee1819a59a1abcc34b8551663a1e61978cfa675

Sorry this took so long, I didn't see this issue till today.. !
