### ISSUE TITLE
Episode boundaries in GPT-4

### ISSUE THREAD

**Issue by anatoleg** [google-deepmind/concordia#46]
FormativeMemoryFactory.add_memories assumes that episodes are separated by '\n\n\n' using this code:
episodes = aggregated_result.split('\n\n\n') - line 216 in formative_memories,py
While defining agents in the three questions example, it complaints that the number of generated episodes does not match the number of formative ages.
I noticed that GPT-4 returns episodes separated by '\n\n' rather than '\n\n\n'.
Changing line 216 to use '\n\n' fixed the problem for me, but it may or may not work for other LLMs.

**Comment by jzleibo** [comment]
Yes, that should work!, exactly
