### ISSUE TITLE
max_steps parameter in GameMaster.run_episode

### ISSUE THREAD

**Issue by anatoleg** [google-deepmind/concordia#61]
When the Conversation component creates a conversation master (convo_scene) it calls convo_scene.run_episode() - line 306
The method has a max_steps parameter (default 25) which we cannot set without modifying the source code.

**Comment by jzleibo** [comment]
Fixed here: https://github.com/google-deepmind/concordia/commit/1254f15ab617aca8d49f491b695f81d44618c074
