### ISSUE TITLE
AttributeError: 'AssociativeMemory' object has no attribute 'sample_text'

### ISSUE THREAD

**Issue by austinmw** [google-deepmind/concordia#67]
![image](https://github.com/google-deepmind/concordia/assets/12224358/1e64f980-73a7-47ab-8814-3e5c446b1f0a)

**Comment by jzleibo** [comment]
Looks like you passed a memory somewhere you were supposed to pass a model?

**Comment by austinmw** [comment]
@jzleibo I did not change any code in the calendar.ipynb example.

**Comment by austinmw** [comment]
Line 43 of the `build_agent` function in `calendar.ipynb` example passes `mem` as the first argument to `BasicAgent`, when it should be `model`.
