### ISSUE TITLE
agent_tutorial.ipynb has an import error

### ISSUE THREAD

**Issue by alcime** [google-deepmind/concordia#77]
After dowloading and uploading on google colab the agent_tutorial.ipynb, running it raises the following error on the second cell of the notebook:

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-4-2237eac7648a>](https://localhost:8080/#) in <cell line: 12>()
     10 
     11 from concordia import typing
---> 12 from concordia.agents import basic_agent
     13 from concordia import components as generic_components
     14 from concordia.components.agent import to_be_deprecated as agent_components

ImportError: cannot import name 'basic_agent' from 'concordia.agents' (/usr/local/lib/python3.10/dist-packages/concordia/agents/__init__.py)

I did execute the previous cell
!pip install --ignore-requires-python git+https://github.com/google-deepmind/concordia.git

**Comment by jzleibo** [comment]
This is fixed now I believe
