### ISSUE TITLE
Agents don't follow their prompts

### ISSUE THREAD

**Issue by ArtemPt239** [google-deepmind/concordia#78]
Hi, I have just run the example `three_key_questions.ipynb` notebook with gpt-4o as a model, and it seems that the agents that are prescribed to be aggressive and conflicting (Alice and Dorothy) completely disregard those prompts and act in a cooperative non-aggressive fashion (exactly how chatgpt acts - "let me apologize for the inconvenience", "I admit I was wrong, let's work together towards a solution").

Is this the intended behavior?

Have you met this kind of issue in your experiments?

**Comment by jzleibo** [comment]
You've discovered that gpt-4o is terrible at role playing. I agree, it is!  They've probably made it so nice by RLHF that it just ignores you when you ask it to role play as a less nice character. Try any other model. Most of them are better at this than gpt-4o.

**Comment by ArtemPt239** [comment]
It would be nice to add a corresponding comment to the tutorial notebook and\or change the default model from gpt-4o to the one which is good at role playing.

**Comment by vezhnick** [comment]
Hey folks, we have fixed togher.ai wrapper and sample_choice should be working a lot better now. Sorry that it took a while.
