### ISSUE TITLE
# @title Display the results log display.HTML(results_log)

### ISSUE THREAD

**Issue by ManooshSamiei** [google-deepmind/concordia#80]
Hello,

I followed all the steps in concordia contest video for my agent development colab notebook.
However when I run display.HTML(results_log)
I get the following error:

`AttributeError: 'tuple' object has no attribute 'lower'`

**Comment by vezhnick** [comment]
Hey Manoosh,

Are you sure you are running the latest version of agent_development.ipynb ? 
runnable_simulation() now returns a tuple where the first output is outcome of the simulation and the second is the hrml log. Should look like this: 
simulation_outcome, results_log = runnable_simulation()
