### ISSUE TITLE
Azure OpenAI support

### ISSUE THREAD

**Issue by ManuelRios18** [google-deepmind/concordia#87]
Hello, we noticed that concordia does not allow the users to use the OpenAI APIs with  the Azure interface. 
We consider that it is important to support Azure given that many companies and universities consume these model using Azure.

**Comment by jzleibo** [comment]
Your pull request looks good to me, I just approved it.  I think that my clicking that button probably kicked off another testing process on our side, and then someone else will have to approve again, and then it'll get merged.

**Comment by ManuelRios18** [comment]
Cool, One of your internal checks failed `feedback/copybara — Google internal checks FAILED for runs with create time 2024-09-26T23:25`. Let us know if we need to do something else from our side.

**Comment by jzleibo** [comment]
Gotcha, I see the issue. I need to log in to our system to run a command to fix it. But unfortunately I'm traveling right now and can't seem to log in. I should be able to do it once I get home on Monday.. Or perhaps @jagapiou or @vezhnick will get to it before I'm back.

**Comment by jagapiou** [comment]
#89 is merged now. Thank you.
